/* script para criar sequence permissao_seq */
CREATE SEQUENCE IF NOT EXISTS permissao_seq START 1;


/* script para criar tabela permissao */
CREATE TABLE IF NOT EXISTS permissao (
	id INTEGER NOT NULL DEFAULT nextval('permissao_seq'),
	descricao VARCHAR(80) NOT NULL,
	CONSTRAINT pk_permissao PRIMARY KEY (id)
);


/* script para inserir registros (permissões para usuario) na tabela permissao */
INSERT INTO permissao (descricao)
	VALUES
		('ROLE_CADASTRAR_USUARIO'),
		('ROLE_PESQUISAR_USUARIO'),
		('ROLE_REMOVER_USUARIO'),
		('ROLE_CADASTRAR_USUARIO_PERMISSAO'),
		('ROLE_PESQUISAR_USUARIO_PERMISSAO'),
		('ROLE_REMOVER_USUARIO_PERMISSAO'),
		('ROLE_CADASTRAR_REGISTRO'),
		('ROLE_PESQUISAR_REGISTRO'),
		('ROLE_REMOVER_REGISTRO'),
		('ROLE_CADASTRAR_ENTRADA_SAIDA'),
		('ROLE_PESQUISAR_ENTRADA_SAIDA'),
		('ROLE_REMOVER_ENTRADA_SAIDA'),
		('ROLE_CADASTRAR_SOLICITACAO_CADASTRO'),
		('ROLE_PESQUISAR_SOLICITACAO_CADASTRO'),
		('ROLE_REMOVER_SOLICITACAO_CADASTRO'),
		('ROLE_CADASTRAR_CONTRATANTE'),
		('ROLE_PESQUISAR_CONTRATANTE'),
		('ROLE_REMOVER_CONTRATANTE'),
		('ROLE_CADASTRAR_PRESTADOR_SERVICO'),
		('ROLE_PESQUISAR_PRESTADOR_SERVICO'),
		('ROLE_REMOVER_PRESTADOR_SERVICO');